function station(){
メトロ=[
`<font color="ff9500">渋谷駅</font>`,
`<font color="ff9500">表参道駅</font>`,
`<font color="ff9500">外苑前駅</font>`,
`<font color="ff9500 ">青山一丁目駅</font>`,
`<font color="ff9500">赤坂見附駅</font>`,
`<font color="ff9500">溜池山王駅</font>`,
`<font color="ff9500">虎ノ門駅</font>`,
`<font color="ff9500">新橋駅</font>`,
`<font color="ff9500">銀座駅</font>`,
`<font color="ff9500">京橋駅</font>`,
`<font color="ff9500">日本橋駅</font>`,
`<font color="ff9500">三越前駅</font>`,
`<font color="ff9500">神田駅</font>`,
`<font color="ff9500">末広町駅</font>`,
`<font color="ff9500">上野広小路駅</font>`,
`<font color="ff9500">上野駅</font>`,
`<font color="ff9500">稲荷町駅</font>`,
`<font color="ff9500">田原町駅</font>`,
`<font color="ff9500">浅草駅</font>`,
//
`<font color="f62e36">荻窪駅</font>`,
`<font color="f62e36">南阿佐ケ谷駅</font>`,
`<font color="f62e36">新高円寺駅</font>`,
`<font color="f62e36">東高円寺駅</font>`,
`<font color="f62e36">新中野駅</font>`,
`<font color="f62e36">中野坂上駅</font>`,
`<font color="f62e36">西新宿駅</font>`,
`<font color="f62e36">新宿駅</font>`,
`<font color="f62e36">新宿三丁目駅</font>`,
`<font color="f62e36">新宿御苑前駅</font>`,
`<font color="f62e36">四谷三丁目駅</font>`,
`<font color="f62e36">四ツ谷駅</font>`,
`<font color="f62e36">赤坂見附駅</font>`,
`<font color="f62e36">国会議事堂前駅</font>`,
`<font color="f62e36">霞ケ関駅</font>`,
`<font color="f62e36">銀座駅</font>`,
`<font color="f62e36">東京駅</font>`,
`<font color="f62e36">大手町駅</font>`,
`<font color="f62e36">淡路町駅</font>`,
`<font color="f62e36">御茶ノ水駅</font>`,
`<font color="f62e36">本郷三丁目駅</font>`,
`<font color="f62e36">後楽園駅</font>`,
`<font color="f62e36">茗荷谷駅</font>`,
`<font color="f62e36">新大塚駅</font>`,
`<font color="f62e36">池袋駅</font>`,
`<font color="f62e36">方南町駅</font>`,
`<font color="f62e36">中野富士見町駅</font>`,
`<font color="f62e36">中野新橋駅</font>`,
`<font color="f62e36">中野坂上駅 </font>`,
//
`<font color="b5b5ac">中目黒駅</font>`,
`<font color="b5b5ac">恵比寿駅</font>`,
`<font color="b5b5ac">広尾駅</font>`,
`<font color="b5b5ac">六本木駅</font>`,
`<font color="b5b5ac">神谷町駅</font>`,
`<font color="b5b5ac">虎ノ門ヒルズ駅</font>`,
`<font color="b5b5ac">霞ケ関駅</font>`,
`<font color="b5b5ac">日比谷駅</font>`,
`<font color="b5b5ac">銀座駅</font>`,
`<font color="b5b5ac">東銀座駅</font>`,
`<font color="b5b5ac">築地駅</font>`,
`<font color="b5b5ac">八丁堀駅</font>`,
`<font color="b5b5ac">茅場町駅</font>`,
`<font color="b5b5ac">人形町駅</font>`,
`<font color="b5b5ac">小伝馬町駅</font>`,
`<font color="b5b5ac">秋葉原駅</font>`,
`<font color="b5b5ac">仲御徒町駅</font>`,
`<font color="b5b5ac">上野駅</font>`,
`<font color="b5b5ac">入谷駅</font>`,
`<font color="b5b5ac">三ノ輪駅</font>`,
`<font color="b5b5ac">南千住駅</font>`,
`<font color="b5b5ac">北千住駅</font>`,
//
`<font color="009bbf ">中野駅</font>`,
`<font color="009bbf ">落合駅</font>`,
`<font color="009bbf ">高田馬場駅</font>`,
`<font color="009bbf ">早稲田駅</font>`,
`<font color="009bbf ">神楽坂駅</font>`,
`<font color="009bbf ">飯田橋駅</font>`,
`<font color="009bbf ">九段下駅</font>`,
`<font color="009bbf ">竹橋駅</font>`,
`<font color="009bbf ">大手町駅</font>`,
`<font color="009bbf ">日本橋駅</font>`,
`<font color="009bbf ">茅場町駅</font>`,
`<font color="009bbf ">門前仲町駅</font>`,
`<font color="009bbf ">木場駅</font>`,
`<font color="009bbf ">東陽町駅</font>`,
`<font color="009bbf ">南砂町駅</font>`,
`<font color="009bbf ">西葛西駅</font>`,
`<font color="009bbf ">葛西駅</font>`,
`<font color="009bbf ">浦安駅</font>`,
`<font color="009bbf ">南行徳駅</font>`,
`<font color="009bbf ">行徳駅</font>`,
`<font color="009bbf ">妙典駅</font>`,
`<font color="009bbf ">原木中山駅</font>`,
`<font color="009bbf ">西船橋駅</font>`,
//
`<font color="00bb85 ">代々木上原駅</font>`,
`<font color="00bb85 ">代々木公園駅</font>`,
`<font color="00bb85 ">明治神宮前駅</font>`,
`<font color="00bb85 ">表参道駅</font>`,
`<font color="00bb85 ">乃木坂駅</font>`,
`<font color="00bb85 ">赤坂駅</font>`,
`<font color="00bb85 ">国会議事堂前駅</font>`,
`<font color="00bb85 ">霞ケ関駅</font>`,
`<font color="00bb85 ">日比谷駅</font>`,
`<font color="00bb85 ">二重橋前駅</font>`,
`<font color="00bb85 ">大手町駅</font>`,
`<font color="00bb85 ">新御茶ノ水駅</font>`,
`<font color="00bb85 ">湯島駅</font>`,
`<font color="00bb85 ">根津駅</font>`,
`<font color="00bb85 ">千駄木駅</font>`,
`<font color="00bb85 ">西日暮里駅</font>`,
`<font color="00bb85 ">町屋駅</font>`,
`<font color="00bb85 ">北千住駅</font>`,
`<font color="00bb85 ">綾瀬駅</font>`,
`<font color="00bb85 ">北綾瀬駅</font>`,
//
`<font color="c1a470 ">和光市駅</font>`,
`<font color="c1a470 ">地下鉄成増駅</font>`,
`<font color="c1a470 ">地下鉄赤塚駅</font>`,
`<font color="c1a470 ">平和台駅</font>`,
`<font color="c1a470 ">氷川台駅</font>`,
`<font color="c1a470 ">小竹向原駅</font>`,
`<font color="c1a470 ">千川駅</font>`,
`<font color="c1a470 ">要町駅</font>`,
`<font color="c1a470 ">池袋駅</font>`,
`<font color="c1a470 ">東池袋駅</font>`,
`<font color="c1a470 ">護国寺駅</font>`,
`<font color="c1a470 ">江戸川橋駅</font>`,
`<font color="c1a470 ">飯田橋駅</font>`,
`<font color="c1a470 ">市ケ谷駅</font>`,
`<font color="c1a470 ">麹町駅</font>`,
`<font color="c1a470 ">永田町駅</font>`,
`<font color="c1a470 ">桜田門駅</font>`,
`<font color="c1a470 ">有楽町駅</font>`,
`<font color="c1a470 ">銀座一丁目駅</font>`,
`<font color="c1a470 ">新富町駅</font>`,
`<font color="c1a470 ">月島駅</font>`,
`<font color="c1a470 ">豊洲駅</font>`,
`<font color="c1a470 ">辰巳駅</font>`,
`<font color="c1a470 ">新木場駅</font>`,
//
`<font color="8f76d6 ">渋谷駅</font>`,
`<font color="8f76d6 ">表参道駅</font>`,
`<font color="8f76d6 ">青山一丁目駅</font>`,
`<font color="8f76d6 ">永田町駅</font>`,
`<font color="8f76d6 ">半蔵門駅</font>`,
`<font color="8f76d6 ">九段下駅</font>`,
`<font color="8f76d6 ">神保町駅</font>`,
`<font color="8f76d6 ">大手町駅</font>`,
`<font color="8f76d6 ">三越前駅</font>`,
`<font color="8f76d6 ">水天宮前駅</font>`,
`<font color="8f76d6 ">清澄白河駅</font>`,
`<font color="8f76d6 ">住吉駅</font>`,
`<font color="8f76d6 ">錦糸町駅</font>`,
`<font color="8f76d6 ">押上駅</font>`,
//
`<font color="00ac9b ">目黒駅</font>`,
`<font color="00ac9b ">白金台駅</font>`,
`<font color="00ac9b ">白金高輪駅</font>`,
`<font color="00ac9b ">麻布十番駅</font>`,
`<font color="00ac9b ">六本木一丁目駅</font>`,
`<font color="00ac9b ">溜池山王駅</font>`,
`<font color="00ac9b ">永田町駅</font>`,
`<font color="00ac9b ">四ツ谷駅</font>`,
`<font color="00ac9b ">市ケ谷駅</font>`,
`<font color="00ac9b ">飯田橋駅</font>`,
`<font color="00ac9b ">後楽園駅</font>`,
`<font color="00ac9b ">東大前駅</font>`,
`<font color="00ac9b ">本駒込駅</font>`,
`<font color="00ac9b ">駒込駅</font>`,
`<font color="00ac9b ">西ケ原駅</font>`,
`<font color="00ac9b ">王子駅</font>`,
`<font color="00ac9b ">王子神谷駅</font>`,
`<font color="00ac9b ">志茂駅</font>`,
`<font color="00ac9b ">赤羽岩淵駅</font>`,
//
`<font color="9c5e31 ">池袋駅</font>`,
`<font color="9c5e31 ">雑司が谷駅</font>`,
`<font color="9c5e31 ">西早稲田駅</font>`,
`<font color="9c5e31 ">東新宿駅</font>`,
`<font color="9c5e31 ">新宿三丁目駅</font>`,
`<font color="9c5e31 ">北参道駅</font>`,
`<font color="9c5e31 ">明治神宮前駅</font>`,
`<font color="9c5e31 ">渋谷駅</font>`
]
メトロ乱数=Math.floor(Math.random() * メトロ.length);



駅=[
`渋谷駅`,
`表参道駅`,
`外苑前駅`,
`青山一丁目駅`,
`赤坂見附駅`,
`溜池山王駅`,
`虎ノ門駅`,
`新橋駅`,
`銀座駅`,
`京橋駅`,
`日本橋駅`,
`三越前駅`,
`神田駅`,
`末広町駅`,
`上野広小路駅`,
`上野駅`,
`稲荷町駅`,
`田原町駅`,
`浅草駅`,
//
`荻窪駅`,
`南阿佐ケ谷駅`,
`新高円寺駅`,
`東高円寺駅`,
`新中野駅`,
`中野坂上駅`,
`西新宿駅`,
`新宿駅`,
`新宿三丁目駅`,
`新宿御苑前駅`,
`四谷三丁目駅`,
`四ツ谷駅`,
`赤坂見附駅`,
`国会議事堂前駅`,
`霞ケ関駅`,
`銀座駅`,
`東京駅`,
`大手町駅`,
`淡路町駅`,
`御茶ノ水駅`,
`本郷三丁目駅`,
`後楽園駅`,
`茗荷谷駅`,
`新大塚駅`,
`池袋駅`,
`方南町駅`,
`中野富士見町駅`,
`中野新橋駅`,
`中野坂上駅 `,
//
`中目黒駅`,
`恵比寿駅`,
`広尾駅`,
`六本木駅`,
`神谷町駅`,
`虎ノ門ヒルズ駅`,
`霞ケ関駅`,
`日比谷駅`,
`銀座駅`,
`東銀座駅`,
`築地駅`,
`八丁堀駅`,
`茅場町駅`,
`人形町駅`,
`小伝馬町駅`,
`秋葉原駅`,
`仲御徒町駅`,
`上野駅`,
`入谷駅`,
`三ノ輪駅`,
`南千住駅`,
`北千住駅`,
//
`中野駅`,
`落合駅`,
`高田馬場駅`,
`早稲田駅`,
`神楽坂駅`,
`飯田橋駅`,
`九段下駅`,
`竹橋駅`,
`大手町駅`,
`日本橋駅`,
`茅場町駅`,
`門前仲町駅`,
`木場駅`,
`東陽町駅`,
`南砂町駅`,
`西葛西駅`,
`葛西駅`,
`浦安駅`,
`南行徳駅`,
`行徳駅`,
`妙典駅`,
`原木中山駅`,
`西船橋駅`,
//
`代々木上原駅`,
`代々木公園駅`,
`明治神宮前駅`,
`表参道駅`,
`乃木坂駅`,
`赤坂駅`,
`国会議事堂前駅`,
`霞ケ関駅`,
`日比谷駅`,
`二重橋前駅`,
`大手町駅`,
`新御茶ノ水駅`,
`湯島駅`,
`根津駅`,
`千駄木駅`,
`西日暮里駅`,
`町屋駅`,
`北千住駅`,
`綾瀬駅`,
`北綾瀬駅`,
//
`和光市駅`,
`地下鉄成増駅`,
`地下鉄赤塚駅`,
`平和台駅`,
`氷川台駅`,
`小竹向原駅`,
`千川駅`,
`要町駅`,
`池袋駅`,
`東池袋駅`,
`護国寺駅`,
`江戸川橋駅`,
`飯田橋駅`,
`市ケ谷駅`,
`麹町駅`,
`永田町駅`,
`桜田門駅`,
`有楽町駅`,
`銀座一丁目駅`,
`新富町駅`,
`月島駅`,
`豊洲駅`,
`辰巳駅`,
`新木場駅`,
//
`渋谷駅`,
`表参道駅`,
`青山一丁目駅`,
`永田町駅`,
`半蔵門駅`,
`九段下駅`,
`神保町駅`,
`大手町駅`,
`三越前駅`,
`水天宮前駅`,
`清澄白河駅`,
`住吉駅`,
`錦糸町駅`,
`押上駅`,
//
`目黒駅`,
`白金台駅`,
`白金高輪駅`,
`麻布十番駅`,
`六本木一丁目駅`,
`溜池山王駅`,
`永田町駅`,
`四ツ谷駅`,
`市ケ谷駅`,
`飯田橋駅`,
`後楽園駅`,
`東大前駅`,
`本駒込駅`,
`駒込駅`,
`西ケ原駅`,
`王子駅`,
`王子神谷駅`,
`志茂駅`,
`赤羽岩淵駅`,
//
`池袋駅`,
`雑司が谷駅`,
`西早稲田駅`,
`東新宿駅`,
`新宿三丁目駅`,
`北参道駅`,
`明治神宮前駅`,
`渋谷駅`
]
駅乱数=Math.floor(Math.random() * 駅.length);
駅乱数2=Math.floor(Math.random() * 駅.length);

if(駅[駅乱数]==駅[駅乱数2]){
station();
}

}